# Generated by Django 5.0.8 on 2024-08-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carsmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='auto_park',
        ),
        migrations.RemoveField(
            model_name='carsmodel',
            name='photo',
        ),
    ]
