# Generated by Django 5.0.7 on 2024-07-27 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carsmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
