# Generated by Django 5.0.7 on 2024-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carsmodel_brand_alter_carsmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='body_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep')], default='Jeep', max_length=10),
            preserve_default=False,
        ),
    ]
