# Generated by Django 5.0.7 on 2024-07-31 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
        ('cars', '0005_carsmodel_body_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='auto_park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_parks.autopark'),
            preserve_default=False,
        ),
    ]
