# Generated by Django 5.0.7 on 2024-08-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carsmodel_options_carsmodel_auto_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
